### ISSUE TITLE
Cannot find module mz/fs

### ISSUE THREAD

**Issue by alangpierce** [decaffeinate/decaffeinate#1251]
From @madskonradsen in https://github.com/decaffeinate/bulk-decaffeinate/issues/142:

I'm about to begin the transition of 1923 CoffeeScript files to TypeScript(yup, that's going to be fun) and already ran into a bug :D It _does_ sound like a decaffeinate bug, but seeing as it was run with bulk-decaffeinate I just suspect that it's something to do with bulk-decaffeinate. Has you experienced anything like that @alangpierce ? Have removed all globally installed packages and re-installed so it doesn't seem like stale modules.

from decaffeinate-errors.log
```
cof.coffee
module.js:557
    throw err;
    ^

Error: Cannot find module 'mz/fs'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/dist/cli.js:5:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/dist/index.js:25:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mads/.nvm/versions/node/v9.3.0/lib/node_modules/decaffeinate/bin/decaffeinate:3:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by alangpierce** [comment]
@madskonradsen I think this must have been from https://github.com/decaffeinate/decaffeinate/pull/1248 from yesterday. We added a usage of `mz/fs` but didn't move it from devDependencies to dependencies. @eventualbuddha could you take care of this?

**Comment by alangpierce** [comment]
@madskonradsen in the meantime, explicitly installing decaffeinate 4.0.1 or maybe 4.0.0 should work.

**Comment by alangpierce** [comment]
I just reran the daily build on open source projects, and it looks like it does break that, so there are tests for this type of problem even if it's not in the PR build. This is kind of a hard thing to test, unfortunately.

**Comment by madskonradsen** [comment]
Yeah I know, but at least the OS projects revealed the bug, albeit a little late :) Btw. Do you know the size of the Benchling/Square/Bugsnag apps that have been converted? Just curious and trying to estimate the conversion of our 1923 files (which we are taken even further by migrating all the way to TS).

**Comment by alangpierce** [comment]
Benchling had 200K lines of CoffeeScript, which was about 1200 files. I wrote up some details here. 😄
https://benchling.engineering/from-200k-lines-of-coffeescript-to-zero-making-decaffeinate-super-stable-4de0ca68d9bc

We're hopefully going to start moving to TS soon, but it seemed best to get off of CoffeeScript before introducing new stuff.

**Comment by eventualbuddha** [comment]
This should be fixed by #1252.

**Comment by madskonradsen** [comment]
Thanks for the link Alan! Lots of things I hadn't thought of! :)

That was a pretty quick fix! Thanks! Also, we are not planning on doing it all at once, but more like Benchling did it :)

I guess we can close this issue.

**Comment by alangpierce** [comment]
👍
