### ISSUE TITLE
`super` doesn't seem to work

### ISSUE THREAD

**Issue by alexgorbatchev** [decaffeinate/decaffeinate#149]
using 1.14.13

```
Error: Syntax error on line 6, column 9: unexpected '\n' (\u000A)
3 :
4 : class Logentries extends winston.Transport
5 :   constructor: (opts) ->
6 :     super
^ :        ^
7 :
8 :     {token, level, levels = winston.levels, secure = true} = opts
9 :
```

**Comment by eventualbuddha** [comment]
The original code from #148 works on master:

```js
class Logentries extends winston.Transport {
  constructor({token, level, levels = winston.levels, secure = true}) {
    super();
    this.name = 'logentries';
  }
}
```

So this is also blocked on #65.

**Comment by alexgorbatchev** [comment]
tried the following

```
$ npm i -g decaffeinate/decaffeinate
...
decaffeinate winston-logentries.coffee
module.js:328
    throw err;
    ^

Error: Cannot find module '../dist/decaffeinate.cjs'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/agorbatchev/.nvm/versions/v5.3.0/lib/node_modules/decaffeinate/bin/decaffeinate:3:1)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by eventualbuddha** [comment]
I wasn't even aware you could do that. Is there a build step that gets triggered when you do that?

**Comment by alexgorbatchev** [comment]
Below is the full NPM log, it goes through all the same motions as regular install... you can pass a number of different things to [`npm install`](https://docs.npmjs.com/cli/install).

```
npm install (with no args, in package dir)
npm install [<@scope>/]<name>
npm install [<@scope>/]<name>@<tag>
npm install [<@scope>/]<name>@<version>
npm install [<@scope>/]<name>@<version range>
npm install <tarball file>
npm install <tarball url>
npm install <folder>

alias: npm i
common options: [-S|--save|-D|--save-dev|-O|--save-optional]
```

NPM LOG

```
$ npm i -g decaffeinate/decaffeinate
/Users/agorbatchev/.nvm/versions/v5.3.0/bin/decaffeinate -> /Users/agorbatchev/.nvm/versions/v5.3.0/lib/node_modules/decaffeinate/bin/decaffeinate
- abbrev@1.0.7 node_modules/decaffeinate/node_modules/abbrev
- cscodegen@0.1.0 node_modules/decaffeinate/node_modules/cscodegen
- estraverse@2.0.0 node_modules/decaffeinate/node_modules/escope/node_modules/estraverse
- esprima@1.1.1 node_modules/decaffeinate/node_modules/esmangle/node_modules/esprima
- escodegen@1.3.3 node_modules/decaffeinate/node_modules/esmangle/node_modules/escodegen
- esprima@1.0.4 node_modules/decaffeinate/node_modules/esprima
- escodegen@1.2.0 node_modules/decaffeinate/node_modules/escodegen
estraverse@4.1.1 node_modules/decaffeinate/node_modules/esshorten/node_modules/estraverse -> node_modules/decaffeinate/node_modules/esrecurse/node_modules/estraverse
- esutils@2.0.2 node_modules/decaffeinate/node_modules/esshorten/node_modules/esutils
- esshorten@1.1.1 node_modules/decaffeinate/node_modules/esshorten
- esmangle@1.0.1 node_modules/decaffeinate/node_modules/esmangle
- nopt@2.1.2 node_modules/decaffeinate/node_modules/nopt
- StringScanner@0.0.3 node_modules/decaffeinate/node_modules/StringScanner
- coffee-script-redux@2.0.0-beta9-dev node_modules/decaffeinate/node_modules/coffee-script-redux
/Users/agorbatchev/.nvm/versions/v5.3.0/lib
└─┬ decaffeinate@1.44.13  (git://github.com/decaffeinate/decaffeinate.git#365c42ac502e052362090b7ab1d8e90b8baf27e2)
  ├─┬ add-variable-declarations@1.3.1
  │ ├─┬ babel-traverse@6.7.3
  │ │ ├─┬ babel-code-frame@6.7.2
  │ │ │ ├── js-tokens@1.0.2
  │ │ │ ├─┬ line-numbers@0.2.0
  │ │ │ │ └── left-pad@0.0.3
  │ │ │ └── repeating@1.1.3
  │ │ ├── babel-messages@6.7.2
  │ │ ├─┬ babel-runtime@5.8.35
  │ │ │ └── core-js@1.2.6
  │ │ ├─┬ invariant@2.2.1
  │ │ │ └── loose-envify@1.1.0
  │ │ ├── lodash@3.10.1
  │ │ └── repeating@1.1.3
  │ └── babylon@6.7.0
  ├─┬ babel-eslint@5.0.0
  │ ├── acorn-to-esprima@2.0.8
  │ ├─┬ babel-types@6.7.2
  │ │ └── to-fast-properties@1.0.1
  │ ├─┬ lodash.assign@3.2.0
  │ │ ├─┬ lodash._baseassign@3.2.0
  │ │ │ └── lodash._basecopy@3.0.1
  │ │ ├─┬ lodash._createassigner@3.1.1
  │ │ │ └── lodash._isiterateecall@3.0.9
  │ │ └── lodash.keys@3.1.2
  │ └─┬ lodash.pick@3.1.0
  │   ├── lodash._baseflatten@3.1.4
  │   ├── lodash._bindcallback@3.0.1
  │   ├── lodash._pickbyarray@3.0.2
  │   ├─┬ lodash._pickbycallback@3.0.0
  │   │ └── lodash._basefor@3.0.3
  │   └── lodash.restparam@3.6.1
  ├── coffee-lex@1.3.4
  ├─┬ decaffeinate-parser@1.2.7
  │ ├── binary-search@1.2.0
  │ └── coffee-script@1.10.0
  ├─┬ eslint@1.10.3
  │ ├─┬ chalk@1.1.1
  │ │ ├─┬ ansi-styles@2.2.0
  │ │ │ └── color-convert@1.0.0
  │ │ ├── has-ansi@2.0.0
  │ │ ├── strip-ansi@3.0.1
  │ │ └── supports-color@2.0.0
  │ ├─┬ concat-stream@1.5.1
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.6
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ ├─┬ doctrine@0.7.2
  │ │ ├── esutils@1.1.6
  │ │ └── isarray@0.0.1
  │ ├── escape-string-regexp@1.0.5
  │ ├─┬ escope@3.6.0
  │ │ ├─┬ es6-map@0.1.3
  │ │ │ ├── d@0.1.1
  │ │ │ ├── es5-ext@0.10.11
  │ │ │ ├── es6-iterator@2.0.0
  │ │ │ ├── es6-set@0.1.4
  │ │ │ ├── es6-symbol@3.0.2
  │ │ │ └── event-emitter@0.3.4
  │ │ ├── es6-weak-map@2.0.1
  │ │ └── esrecurse@4.1.0
  │ ├── espree@2.2.5
  │ ├── estraverse@4.2.0
  │ ├── estraverse-fb@1.3.1
  │ ├── esutils@2.0.2
  │ ├─┬ file-entry-cache@1.2.4
  │ │ └─┬ flat-cache@1.0.10
  │ │   ├─┬ del@2.2.0
  │ │   │ ├─┬ globby@4.0.0
  │ │   │ │ ├─┬ array-union@1.0.1
  │ │   │ │ │ └── array-uniq@1.0.2
  │ │   │ │ ├── arrify@1.0.1
  │ │   │ │ └── glob@6.0.4
  │ │   │ ├── is-path-cwd@1.0.0
  │ │   │ ├─┬ is-path-in-cwd@1.0.0
  │ │   │ │ └── is-path-inside@1.0.0
  │ │   │ ├── pify@2.3.0
  │ │   │ ├─┬ pinkie-promise@2.0.0
  │ │   │ │ └── pinkie@2.0.4
  │ │   │ └─┬ rimraf@2.5.2
  │ │   │   └── glob@7.0.3
  │ │   ├── graceful-fs@4.1.3
  │ │   ├── read-json-sync@1.1.1
  │ │   └── write@0.2.1
  │ ├─┬ glob@5.0.15
  │ │ ├─┬ inflight@1.0.4
  │ │ │ └── wrappy@1.0.1
  │ │ └── once@1.3.3
  │ ├── globals@8.18.0
  │ ├─┬ handlebars@4.0.5
  │ │ ├── async@1.5.2
  │ │ ├── optimist@0.6.1
  │ │ ├── source-map@0.4.4
  │ │ └─┬ uglify-js@2.6.2
  │ │   ├── async@0.2.10
  │ │   ├── source-map@0.5.3
  │ │   ├── uglify-to-browserify@1.0.2
  │ │   └─┬ yargs@3.10.0
  │ │     ├── camelcase@1.2.1
  │ │     ├─┬ cliui@2.1.0
  │ │     │ ├─┬ center-align@0.1.3
  │ │     │ │ ├─┬ align-text@0.1.4
  │ │     │ │ │ ├─┬ kind-of@3.0.2
  │ │     │ │ │ │ └── is-buffer@1.1.3
  │ │     │ │ │ ├── longest@1.0.1
  │ │     │ │ │ └── repeat-string@1.5.4
  │ │     │ │ └── lazy-cache@1.0.3
  │ │     │ ├── right-align@0.1.3
  │ │     │ └── wordwrap@0.0.2
  │ │     ├── decamelize@1.2.0
  │ │     └── window-size@0.1.0
  │ ├─┬ inquirer@0.11.4
  │ │ ├── ansi-escapes@1.3.0
  │ │ ├── ansi-regex@2.0.0
  │ │ ├─┬ cli-cursor@1.0.2
  │ │ │ └─┬ restore-cursor@1.0.1
  │ │ │   ├── exit-hook@1.1.1
  │ │ │   └── onetime@1.1.0
  │ │ ├── cli-width@1.1.1
  │ │ ├── figures@1.4.0
  │ │ ├─┬ readline2@1.0.1
  │ │ │ ├── code-point-at@1.0.0
  │ │ │ ├── is-fullwidth-code-point@1.0.0
  │ │ │ └── mute-stream@0.0.5
  │ │ ├── run-async@0.1.0
  │ │ ├── rx-lite@3.1.2
  │ │ ├── string-width@1.0.1
  │ │ └── through@2.3.8
  │ ├─┬ is-my-json-valid@2.13.1
  │ │ ├── generate-function@2.0.0
  │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ └── is-property@1.0.2
  │ │ ├── jsonpointer@2.0.0
  │ │ └── xtend@4.0.1
  │ ├─┬ is-resolvable@1.0.0
  │ │ └── tryit@1.0.2
  │ ├─┬ js-yaml@3.4.5
  │ │ ├─┬ argparse@1.0.7
  │ │ │ └── sprintf-js@1.0.3
  │ │ └── esprima@2.7.2
  │ ├─┬ json-stable-stringify@1.0.1
  │ │ └── jsonify@0.0.0
  │ ├─┬ lodash.clonedeep@3.0.2
docker-machine-restart() {
  │ │ └── lodash._baseclone@3.3.0
  │ ├─┬ lodash.merge@3.3.2
  │ │ ├── lodash._arraycopy@3.0.0
  │ │ ├── lodash._arrayeach@3.0.0
  │ │ ├── lodash._getnative@3.9.1
  │ │ ├── lodash.isarguments@3.0.8
  │ │ ├── lodash.isarray@3.0.4
  │ │ ├── lodash.isplainobject@3.2.0
  │ │ ├── lodash.istypedarray@3.0.5
  │ │ ├── lodash.keysin@3.0.8
  │ │ └── lodash.toplainobject@3.0.0
  │ ├─┬ lodash.omit@3.1.0
  │ │ ├── lodash._arraymap@3.0.0
  │ │ └─┬ lodash._basedifference@3.0.3
  │ │   ├── lodash._baseindexof@3.1.0
  │ │   ├── lodash._cacheindexof@3.0.2
  │ │   └── lodash._createcache@3.1.2
  │ ├─┬ minimatch@3.0.0
  │ │ └─┬ brace-expansion@1.1.3
  │ │   ├── balanced-match@0.3.0
  │ │   └── concat-map@0.0.1
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├── object-assign@4.0.1
  │ ├── optionator@0.6.0
  │ ├── path-is-absolute@1.0.0
  │ ├── path-is-inside@1.0.1
  │ ├── shelljs@0.5.3
  │ ├── strip-json-comments@1.0.4
  │ ├── text-table@0.2.0
  │ ├─┬ user-home@2.0.0
  │ │ └── os-homedir@1.0.1
  │ └── xml-escape@1.0.0
  └─┬ esnext@1.15.8
    ├── shebang-regex@2.0.0
    └─┬ strip-indent@1.0.1
      └── get-stdin@4.0.1
```

**Comment by eventualbuddha** [comment]
Hmm… well, since there's a build step that `npm` is not executing the `dist/` file will not be there. Probably better to just `git clone https://github.com/decaffeinate/decaffeinate.git && cd decaffeinate && npm install && npm link`.

**Comment by alexgorbatchev** [comment]
That worked, my `.coffee` compiled. 

I'm a bit surprised to be honest with you since it still involves exactly the same `npm install` command, just the order of things is a bit different... there's probably a bug in NPM somewhere.

**Comment by eventualbuddha** [comment]
This now works in v2.7.4, and probably earlier.
