### ISSUE TITLE
Error: Cannot use replaced characters as slice anchors

### ISSUE THREAD

**Issue by alexgorbatchev** [decaffeinate/decaffeinate#150]
Using version https://github.com/decaffeinate/decaffeinate/commit/365c42ac502e052362090b7ab1d8e90b8baf27e2

Input file

```coffeescript
logentries = require 'logentries'
require 'coffee-errors'

chai = require 'chai'
winston = require 'winston'
sinon = require 'sinon'
{Logentries} = require '../src/winston-logentries'

expect = chai.expect
chai.use require 'sinon-chai'

describe 'Logentries options', ->
  spy = sinon.spy logentries, "logger"
  i = 0

  it 'can set token', ->
    transport = new Logentries token: 'test'
    expect(spy.args[i][0].token).to.equal "test"
    i++

  it 'defaults to secure transport', ->
    transport = new Logentries token: ''
    expect(spy.args[i][0].secure).to.equal true
    i++

  it 'can use insecure transport', ->
    transport = new Logentries token: '', secure: false
    expect(spy.args[i][0].secure).to.equal false
    i++

  it 'adopts log levels from winston', ->
    transport = new Logentries token: '', secure: false
    expect(transport.logentries.levels).to.be.equal winston.levels
    i++

  it 'defaults to level `info`', ->
    levels =
      level0: 0
      level1: 1
    transport = new Logentries token: ''
    expect(transport.level).to.equal "info"
    i++

  it 'can set custom levels', ->
    levels =
      level0: 0
      level1: 1
    transport = new Logentries token: '', level: "level0", levels: levels
    expect(transport.level).to.equal "level0"
    expect(spy.args[i][0].levels).to.equal levels
    i++

describe 'Logentries log levels', ->
  logger = null
  transport = null

  beforeEach ->
    transport = new Logentries token: ''
    logger = new winston.Logger transports: [transport]

    sinon.spy transport.logentries, 'log'

  it 'calls service `log` method without meta', ->
    logger.info 'hello!'
    expect(transport.logentries.log).to.have.been.calledWith 'info', 'hello!'

  it 'calls service `log` method with meta', ->
    logger.info 'hello!', foo: 123
    expect(transport.logentries.log).to.have.been.calledWith 'info', 'hello! {"foo":123}'

  it 'calls `log` method with `warning` level which has been translated from  `warn`', ->
    logger.warn 'hello!', foo: 123
    expect(transport.logentries.log).to.have.been.calledWith 'warning', 'hello! {"foo":123}'

  it 'calls `log` method with `err` level which has been translated from  `error`', ->
    logger.error 'hello!', foo: 123
    expect(transport.logentries.log).to.have.been.calledWith 'err', 'hello! {"foo":123}'
```

Error:

```
$ decaffeinate winston-logentries.spec.coffee
winston-logentries.spec.coffee → winston-logentries.spec.js
/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:6965
        throw err;
        ^

Error: Cannot use replaced characters (571, 575) as slice anchors
  at Object.slice (/Users/agorbatchev/1/decaffeinate/node_modules/magic-string/dist/magic-string.cjs.js:482:57)
  at BoolPatcher.slice (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:819:26)
  at BoolPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1705:20)
  at BoolPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:636:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3776:13
  at Array.forEach (native)
  at FunctionApplicationPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3775:17)
  at FunctionApplicationPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3788:12)
  at FunctionApplicationPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1589:19
  at Array.forEach (native)
  at BlockPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1581:23)
  at BlockPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at FunctionPatcher.patchFunctionBody (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1804:19)
  at FunctionPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1780:12)
  at FunctionPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:636:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3776:13
  at Array.forEach (native)
  at FunctionApplicationPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3775:17)
  at FunctionApplicationPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3788:12)
  at FunctionApplicationPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1589:19
  at Array.forEach (native)
  at BlockPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1581:23)
  at BlockPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at FunctionPatcher.patchFunctionBody (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1804:19)
  at FunctionPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1780:12)
  at FunctionPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:636:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3776:13
  at Array.forEach (native)
  at FunctionApplicationPatcher.patchAsExpression (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3775:17)
  at FunctionApplicationPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:3788:12)
  at FunctionApplicationPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1589:19
  at Array.forEach (native)
  at BlockPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:1581:23)
  at BlockPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at ProgramPatcher.patchAsStatement (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:4483:17)
  at ProgramPatcher.patch (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:638:14)
  at Function.run (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:6013:15)
  at /Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:7027:28
  at Array.forEach (native)
  at runStages (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:7026:10)
  at convert$1 (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:7019:10)
  at ReadStream.<anonymous> (/Users/agorbatchev/1/decaffeinate/dist/decaffeinate.cjs.js:6959:19)
  at emitNone (events.js:72:20)
  at ReadStream.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:455:9)
  at process._tickCallback (node.js:369:17)
```

**Comment by eventualbuddha** [comment]
After running with #152 applied I get this error:

```
stdin: Cannot use replaced characters (571, 575) as slice anchors
  21 |   it 'defaults to secure transport', ->
  22 |     transport = new Logentries token: ''
> 23 |     expect(spy.args[i][0].secure).to.equal true
     |                                            ^^^^
  24 |     i++
  25 | 
```

I'll look into what's causing the issue.

**Comment by eventualbuddha** [comment]
After running with #153 applied I get this output:

```js
import logentries from 'logentries';
import 'coffee-errors';

import chai from 'chai';
import winston from 'winston';
import sinon from 'sinon';
import { Logentries } from '../src/winston-logentries';

let { expect } = chai;
chai.use(require('sinon-chai'));

describe('Logentries options', function() {
  let spy = sinon.spy(logentries, "logger");
  let i = 0;

  it('can set token', function() {
    let transport = new Logentries({token: 'test'});
    expect(spy.args[i][0].token).to.equal("test");
    return i++;
  });

  it('defaults to secure transport', function() {
    let transport = new Logentries({token: ''});
    expect(spy.args[i][0].secure).to.equal(true);
    return i++;
  });

  it('can use insecure transport', function() {
    let transport = new Logentries({token: '', secure: false});
    expect(spy.args[i][0].secure).to.equal(false);
    return i++;
  });

  it('adopts log levels from winston', function() {
    let transport = new Logentries({token: '', secure: false});
    expect(transport.logentries.levels).to.be.equal(winston.levels);
    return i++;
  });

  it('defaults to level `info`', function() {
    let levels =
      {level0: 0,
      level1: 1};
    let transport = new Logentries({token: ''});
    expect(transport.level).to.equal("info");
    return i++;
  });

  return it('can set custom levels', function() {
    let levels =
      {level0: 0,
      level1: 1};
    let transport = new Logentries({token: '', level: "level0", levels});
    expect(transport.level).to.equal("level0");
    expect(spy.args[i][0].levels).to.equal(levels);
    return i++;
  });
});

describe('Logentries log levels', function() {
  let logger = null;
  let transport = null;

  beforeEach(function() {
    transport = new Logentries({token: ''});
    logger = new winston.Logger({transports: [transport]});

    return sinon.spy(transport.logentries, 'log');
  });

  it('calls service `log` method without meta', function() {
    logger.info('hello!');
    return expect(transport.logentries.log).to.have.been.calledWith('info', 'hello!');
  });

  it('calls service `log` method with meta', function() {
    logger.info('hello!', {foo: 123});
    return expect(transport.logentries.log).to.have.been.calledWith('info', 'hello! {"foo":123}');
  });

  it('calls `log` method with `warning` level which has been translated from  `warn`', function() {
    logger.warn('hello!', {foo: 123});
    return expect(transport.logentries.log).to.have.been.calledWith('warning', 'hello! {"foo":123}');
  });

  return it('calls `log` method with `err` level which has been translated from  `error`', function() {
    logger.error('hello!', {foo: 123});
    return expect(transport.logentries.log).to.have.been.calledWith('err', 'hello! {"foo":123}');
  });
});
```
