### ISSUE TITLE
decaffeinate crashes with a thin arrow function in an object

### ISSUE THREAD

**Issue by uasi** [decaffeinate/decaffeinate#1622]
decaffeinate is crashing on my CoffeeScript input:

```coffee
# Bad
prop: (x) -> x

# OK
#prop: (x) => x

# Also OK
#func((x) -> x)
```

if Babel is configured to target fairly old browsers as follows:

```js
// babel.config.js

module.exports = {
  presets: [
    // Bad
    ["@babel/preset-env", { targets: ["IE 11"] }],
    // OK
    //["@babel/preset-env", { targets: ["last 1 Chrome version"] }],
  ],
};
```

Minimal reproducible setup is here https://gitlab.com/uasi/20191112-decaffeinate-crash

I get this error:

```
/Users/uasi/tmp/decaf/node_modules/decaffeinate/dist/cli.js:304
        throw err;
        ^

RangeError: unknown: Maximum call stack size exceeded
    at Object.get [as isBlockScoped] (/Users/uasi/tmp/decaf/node_modules/@babel/types/lib/index.js:286:17)
    at Object.checkPath (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/lib/virtual-types.js:118:14)
    at Object.newFn (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/visitors.js:215:17)
    at NodePath._call (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:38:14)
    at NodePath.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitMultiple (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:79:17)
    at TraversalContext.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:138:19)
    at Function.traverse.node (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/index.js:84:17)
    at NodePath.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:97:18)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/index.js:66:12)
    at NodePath.traverse (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/index.js:148:24)
    at Scope.crawl (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/scope/index.js:639:10)
    at Scope.init (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/scope/index.js:589:32)
    at NodePath.setScope (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:131:30)
    at NodePath.replaceWith (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/replacement.js:159:8)
    at PluginPass.ObjectProperty (/Users/uasi/tmp/decaf/node_modules/@resugar/codemod-objects-concise/src/index.js:20:22)
    at newFn (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:118:21)
    at TraversalContext.visitQueue (/Users/uasi/tmp/decaf/node_modules/@babel/traverse/lib/context.js:118:21)


...
```

**Comment by uasi** [comment]
Within the repro dir, `yarn add -D decaffeinate@6.0.1` fixes the issue but `yarn add -D decaffeinate@6.0.2` does not. I suppose this commit broke something https://github.com/decaffeinate/decaffeinate/commit/16da52422b8e587da804b280568d1c5d0ff01297

**Comment by eventualbuddha** [comment]
That commit did change a fair amount of how decaffeinate works, so it’s not surprising to me it’d change the behavior. However, I don’t think this is an issue with decaffeinate itself so much as an interaction with other tools like babel. See how [decaffeinate handles your example just fine on its own](https://decaffeinate-project.org/repl/#?useCS2=true&useJSModules=false&loose=false&evaluate=true&stage=full&code=prop%3A%20(x)%20-%3E%20x). If I get a chance I’ll check out the example repo (thanks for that!), but I don’t have a lot of time for decaffeinate these days.

**Comment by joker-777** [comment]
Hello, any progress here? I get the same error.

**Comment by joker-777** [comment]
In my case it brakes with this code

```coffee
test =
  bla: ->
  
  blub: ->
    test.bla()

export default test
```

**Comment by joker-777** [comment]
BTW, it only happens when `@babel/preset-env` is set in `babel.config.js`.

**Comment by uasi** [comment]
I think I found the root cause.

We can reproduce this bug only using the `@babel/plugin-transform-shorthand-properties` plugin.

```js
// babel.config.js

module.exports = {
  plugins: [
    ["@babel/plugin-transform-shorthand-properties"],
  ],
}
```

It transforms concise methods to longer form (`{ func() {...} }` -> `{ func: function() {...} }`), while the `@resugar/codemod-objects-concise` plugin used by decaffeinate does the opposite.

- https://github.com/babel/babel/blob/v7.8.3/packages/babel-plugin-transform-shorthand-properties/src/index.js#L11-L25
- https://github.com/resugar/resugar/blob/83f1ead58ee01992b8bc571f7e510512bf24a164/packages/resugar-codemod-objects-concise/src/index.ts#L9-L24

Maybe these plugins rewrite each other's output endlessly.

**Comment by joker-777** [comment]
@eventualbuddha It would be great if you could have a look.

**Comment by uasi** [comment]
I confirmed that `@babel/plugin-transform-shorthand-properties` and `@resugar/codemod-objects-concise` do conflict:

```js
// babel.config.js

module.exports = {
  plugins: [
    "module:@resugar/codemod-objects-concise",
    "@babel/plugin-transform-shorthand-properties",
  ]
}
```

```
$ echo '({ func() {} })' | node_modules/.bin/babel --no-babelrc

{ RangeError: unknown: Maximum call stack size exceeded
    at NodePath._call (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitQueue (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/context.js:118:21)
[snip]
    at TraversalContext.visitQueue (/Users/uasi/tmp/r/node_modules/@babel/traverse/lib/context.js:118:21) code: 'BABEL_TRANSFORM_ERROR' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by joker-777** [comment]
@uasi Do you know a way to run `decaffeinate` without `@babel/plugin-transform-shorthand-properties` without modifying `babel.config.js`?

**Comment by uasi** [comment]
@joker-777 No, but you can use `decaffeinate@6.0.1` in the meantime.

**Comment by joker-777** [comment]
Thanks, I did but I actually got a different error there which is fixed with the lastest version.

**Comment by joker-777** [comment]
I found out that the `transform-destructuring` babel plugin creates also this error.
