### ISSUE TITLE
"Unexpected token" traceback on coffeescript objects with quotes in the keys

### ISSUE THREAD

**Issue by danielbprice** [decaffeinate/decaffeinate#178]
The following appears to pass the coffeescript compiler without complaint:

`x = {"FOO", "BAR", "BAZ"}`

Resulting in:

```javascript
// Generated by CoffeeScript 1.10.0
(function() {
  var x;

  x = {
    "FOO": "FOO",
    "BAR": "BAR",
    "BAZ": "BAZ"
  };

}).call(this);
```

However if I call the same with decaffeinate:

```
echo 'x = {"FOO", "BAR", "BAZ"}' | bin/decaffeinate
/tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8691
        throw err;
        ^

SyntaxError: Unexpected token (1:10)
  at Parser.pp.raise (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:1378:13)
  at Parser.pp.unexpected (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:2817:8)
  at Parser.pp.parseObjPropValue (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:1059:8)
  at Parser.parseObjPropValue (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:3775:13)
  at Parser.pp.parseObj (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:989:10)
  at Parser.pp.parseExprAtom (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:718:19)
  at Parser.parseExprAtom (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:4305:22)
  at Parser.pp.parseExprSubscripts (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:504:19)
  at Parser.pp.parseMaybeUnary (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:484:19)
  at Parser.pp.parseExprOps (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:415:19)
  at Parser.pp.parseMaybeConditional (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:397:19)
  at Parser.pp.parseMaybeAssign (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:360:19)
  at Parser.pp.parseMaybeAssign (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:383:23)
  at Parser.pp.parseExpression (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:324:19)
  at Parser.pp.parseStatement (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:1874:19)
  at Parser.parseStatement (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:3507:22)
  at Parser.pp.parseBlockBody (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:2208:21)
  at Parser.pp.parseTopLevel (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:1747:8)
  at Parser.parse (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:1349:17)
  at Object.parse (/tmp/dp/node_modules/decaffeinate/node_modules/babylon/index.js:45:50)
  at addVariableDeclarations (/tmp/dp/node_modules/decaffeinate/node_modules/add-variable-declarations/dist/add-variable-declarations.umd.js:246:77)
  at Function.run (/tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:180:7)
  at /tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8754:28
  at Array.forEach (native)
  at runStages (/tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8753:10)
  at convert$1 (/tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8746:10)
  at Socket.<anonymous> (/tmp/dp/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8685:19)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:913:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)
```

On the other hand:

```
echo "x = {FOO, BAR, BAZ}" | bin/decaffeinate
let x = {FOO, BAR, BAZ};
```

Works fine, as expected.

This is with decaffeinate@2.7.3.  (We have a very large coffeescript project and I am just evaluating what it would take to convert it, and this is the first problem I hit).

**Comment by eventualbuddha** [comment]
Fixed in v2.7.5 ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=x%20%3D%20%7B%22FOO%22%2C%20%22BAR%22%2C%20%22BAZ%22%7D)). In addition, this version fixes `x = {"a#{b}c"}` which I didn't even know was possible before. Thanks for reporting the issue, and let me know if you encounter anything else while converting your project!
