### ISSUE TITLE
Package dies on functions

### ISSUE THREAD

**Issue by flanger001** [decaffeinate/decaffeinate#1911]
decaffeinate is crashing on my CoffeeScript input but only on the command line:

```coffee
foo: -> true
```

It works in the [repl](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&evaluate=true&stage=full&code=foo%3A%20-%3E%20true), but when I run it, I get this error:

```
> yarn decaffeinate test.coffee                                                                        
yarn run v1.22.0
warning package.json: No license field
$ /Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/.bin/decaffeinate test.coffee
test.coffee → test.js
(node:90490) UnhandledPromiseRejectionWarning: RangeError: unknown: Maximum call stack size exceeded
    at NodePath._call (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitSingle (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:140:19)
    at Function.traverse.node (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/index.js:84:17)
    at traverse (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/index.js:66:12)
    at NodePath.traverse (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/index.js:148:24)
    at Scope.crawl (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/scope/index.js:735:10)
    at Scope.init (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/scope/index.js:685:32)
    at NodePath.setScope (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:131:30)
    at NodePath.replaceWith (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/replacement.js:159:8)
    at PluginPass.ObjectProperty (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@resugar/codemod-objects-concise/src/index.js:20:22)
    at newFn (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/path/context.js:90:31)
    at TraversalContext.visitQueue (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitQueue (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:112:16)
    at TraversalContext.visitQueue (/Users/davidshaffer/Dropbox/Coding/Personal/dc/node_modules/@babel/traverse/lib/context.js:112:16)

```

It repeats the `TraversalContext.visitQueue` thing about 3000 times, then fails

It looks to me like the `->` function syntax is the issue, as this was the minimum input I needed to reproduce it.

**Comment by flanger001** [comment]
Looks like this is a dup of https://github.com/decaffeinate/decaffeinate/issues/1622
