### ISSUE TITLE
Some string interpolations are rewritten incorrectly

### ISSUE THREAD

**Issue by eventualbuddha** [decaffeinate/decaffeinate#195]
The example from #58, for example. Note that the `#`s should be turned into `$`s but not all of them are, and some characters that are not `#` are rewritten.

```
NormalizeStage rs.say "Collecting trigger list for topic #{topic} (depth=#{depth}; " \
    + "inheritance=#{inheritance}; inherited=#{inherited})"
MainStage rs.say "Collecting trigger list for topic #{topic} (depth=#{depth}; " \
    + "inheritance=#{inheritance}; inherited=#{inherited})"
FunctionApplicationPatcher OVERWRITE [6, 7) " " → "("
TemplateLiteralPatcher OVERWRITE [7, 8) "\"" → "`"
TemplateLiteralPatcher OVERWRITE [68, 69) "\"" → "`"
TemplateLiteralPatcher OVERWRITE [42, 43) "#" → "$"
TemplateLiteralPatcher OVERWRITE [50, 51) " " → "$"
TemplateLiteralPatcher OVERWRITE [69, 70) " " → "$"
TemplateLiteralPatcher OVERWRITE [78, 79) "\"" → "`"
TemplateLiteralPatcher OVERWRITE [130, 131) "\"" → "`"
TemplateLiteralPatcher OVERWRITE [91, 92) "#" → "$"
TemplateLiteralPatcher OVERWRITE [117, 118) "#" → "$"
FunctionApplicationPatcher INSERT 131 ")" BEFORE ""
BlockPatcher INSERT 131 ";" BEFORE ""
ProgramPatcher REMOVE [70, 71) "\\"
AddVariableDeclarationsStage rs.say(`Collecting trigger list for topic ${topic}$(depth=#{depth}; `$
    + `inheritance=${inheritance}; inherited=${inherited})`);
/Users/donovan/src/com.brian-donovan/decaffeinate/dist/decaffeinate.cjs.js:8763
        throw err;
        ^

SyntaxError: Unexpected token (1:69)
  at Parser.pp.raise (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:1378:13)
  at Parser.pp.unexpected (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:2817:8)
  at Parser.pp.expect (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:2811:33)
  at Parser.pp.parseCallExpressionArguments (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:571:12)
  at Parser.pp.parseSubscripts (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:543:29)
  at Parser.pp.parseExprSubscripts (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:514:15)
  at Parser.pp.parseMaybeUnary (/Users/donovan/src/com.brian-donovan/decaffeinate/node_modules/babylon/index.js:484:19)
  at Parser.pp.parseExprOps (/
```

**Comment by alangpierce** [comment]
Looks like this was fixed by https://github.com/decaffeinate/decaffeinate-parser/pull/71. [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=rs.say%20%22Collecting%20trigger%20list%20for%20topic%20%23%7Btopic%7D%20(depth%3D%23%7Bdepth%7D%3B%20%22%20%5C%0A%20%20%20%20%2B%20%22inheritance%3D%23%7Binheritance%7D%3B%20inherited%3D%23%7Binherited%7D)%22)
