### ISSUE TITLE
Default arguments in classes causes parse error

### ISSUE THREAD

**Issue by sethyates** [decaffeinate/decaffeinate#232]
```
$ cat animal.coffee
module.exports = class Animal
  constructor: (@name = 'kangaroo') ->

  move: (meters) ->
    alert @name + " moved #{meters}m."

$ decaffeinate animal.coffee
animal.coffee → animal.js
/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8840
        throw err;
        ^

SyntaxError: Unexpected token (2:14)
  at Parser.pp.raise (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/location.js:22:13)
  at Parser.pp.unexpected (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/util.js:89:8)
  at Parser.pp.parseBindingAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/lval.js:177:12)
  at Parser.pp.parseMaybeDefault (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/lval.js:223:23)
  at Parser.pp.parseBindingList (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/lval.js:203:23)
  at Parser.pp.parseMethod (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:880:22)
  at Parser.parseClassMethod (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:258:12)
  at Parser.pp.parseClassBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:784:10)
  at Parser.pp.parseClass (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:666:8)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:497:19)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:272:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:252:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:183:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:151:23)
  at Parser.pp.parseExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:92:19)
  at Parser.pp.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:163:19)
  at Parser.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:30:22)
  at Parser.pp.parseBlockBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:529:21)
  at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:36:8)
  at Parser.parse (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/index.js:129:19)
  at Object.parse (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/index.js:47:47)
  at addVariableDeclarations (/usr/local/lib/node_modules/decaffeinate/node_modules/add-variable-declarations/dist/add-variable-declarations.umd.js:212:77)
  at Function.run (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:180:7)
  at /usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8906:28
  at Array.forEach (native)
  at runStages (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8905:10)
  at convert$1 (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8898:10)
  at ReadStream.<anonymous> (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:8834:19)
  at emitNone (events.js:85:20)
  at ReadStream.emit (events.js:179:7)
  at endReadableNT (_stream_readable.js:913:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by madskonradsen** [comment]
Just adding a link to the REPL with the code :)

http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=module.exports%20%3D%20class%20Animal%0A%20%20constructor%3A%20(%40name%20%3D%20'kangaroo')%20-%3E%0A%0A%20%20move%3A%20(meters)%20-%3E%0A%20%20%20%20alert%20%40name%20%2B%20%22%20moved%20%23%7Bmeters%7Dm.%22%0A

**Comment by hsandt** [comment]
I had the same error, it only happens when combining the constructor member sugar syntax (@) with the default value syntax. Using only the default value in a constructor (or another method):

`constructor: (name = 'kangaroo') ->
    @name = name`


or only the member sugar syntax without a default value:

`constructor: (@name) ->`

the code is correctly converted.

I created a smaller example showing the error: http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=class%20Animal%0D%0A%20%20constructor%3A%20(%40name%20%3D%20'kangaroo')%20-%3E%0D%0A

Also, the error message is now more precise:

> AddVariableDeclarationsStage failed to parse: Unexpected token (256:27).

I suggest to rename the issue "Default value in class constructor using '@' syntactic sugar causes parsing error in AddVariableDeclarationsStage" or something like this, to facilitate searches by keyword.

Until the issue is solved, I will probably remove the default values and add them again by hand after the conversion.
