### ISSUE TITLE
Fails to parse files that begin with newlines

### ISSUE THREAD

**Issue by marshall007** [decaffeinate/decaffeinate#236]
```
$ echo "\n\nPromise = require 'bluebird'" | decaffeinate

/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9025
        throw err;
        ^

Error: unexpected 'null' index, perhaps you forgot to check the result of 'indexOfTokenContainingSourceIndex'?
  at SourceTokenList._validateIndex (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/coffee-lex/dist/coffee-lex.umd.js:628:17)
  at SourceTokenList.tokenAtIndex (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/coffee-lex/dist/coffee-lex.umd.js:346:14)
  at makeNode (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1730:54)
  at convertNode (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1211:22)
  at convertChild (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1681:18)
  at convertNode (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1164:23)
  at convertChild (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1681:18)
  at /Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1269:27
  at convertNode (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1298:14)
  at convertChild (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1681:18)
  at Array.map (native)
  at convertChild (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1677:24)
  at convertNode (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:1148:25)
  at convert (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:960:12)
  at Object.parse (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:881:33)
  at parse$2 (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:7190:32)
  at Function.run (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:7222:17)
  at /Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9091:28
  at Array.forEach (native)
  at runStages (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9090:10)
  at convert$1 (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9083:10)
  at Socket.<anonymous> (/Users/marshall/.nvm/versions/node/v4.2.2/lib/node_modules/decaffeinate/dist/decaffeinate.cjs.js:9019:19)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at doNTCallback2 (node.js:441:9)
  at process._tickCallback (node.js:355:17)
```

**Comment by madskonradsen** [comment]
Same as #226

**Comment by marshall007** [comment]
@madskonradsen oops, thanks!

**Comment by madskonradsen** [comment]
To be fair i also JUST renamed #226 to something a tad more meaningful, so i get why didn't see it ;)
