### ISSUE TITLE
Lexer error around an object literal in a certain position: unexpected EOF while in context PAREN

### ISSUE THREAD

**Issue by qnighy** [decaffeinate/decaffeinate#2413]
decaffeinate is crashing on my CoffeeScript input:

```coffee
foo ->
  bar
    baz: 42,
```

[Link to Decaffeinate REPL](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&optionalChaining=false&evaluate=true&stage=full&code=foo%20-%3E%0A%20%20bar%0A%20%20%20%20baz%3A%2042%2C)

[Link to Try CoffeeScript](https://coffeescript.org/#try:foo%20-%3E%0A%20%20bar%0A%20%20%20%20baz%3A%2042%2C%0A)

I get this error:

```
test.coffee → test.js
/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/index.js:763
                        throw new Error("unexpected EOF while in context " + context.type);
                              ^

Error: unexpected EOF while in context PAREN
    at BufferedStream.step [as _getNextLocation] (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/index.js:763:31)
    at BufferedStream.shift (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/utils/BufferedStream.js:9:45)
    at /Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/utils/BufferedStream.js:19:30
    at Array.every (<anonymous>)
    at BufferedStream.hasNext (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/utils/BufferedStream.js:18:28)
    at Object.calculateNormalStringPadding [as default] (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/utils/calculateNormalStringPadding.js:16:16)
    at Object.lex [as default] (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/coffee-lex/dist/index.js:42:78)
    at sourceLex (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate-parser/dist/parser.js:19:39)
    at Function.ParseContext.fromSource (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate-parser/dist/util/ParseContext.js:94:32)
    at Object.parse (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate-parser/dist/parser.js:21:45)
    at Function.DecaffeinateContext.create (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/utils/DecaffeinateContext.js:21:45)
    at Function.TransformCoffeeScriptStage.run (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/stages/TransformCoffeeScriptStage.js:22:53)
    at runStage (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/index.js:97:22)
    at /Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/index.js:89:18
    at Array.forEach (<anonymous>)
    at runStages (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/index.js:88:12)
    at Object.convert (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/index.js:61:18)
    at runWithCode (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/cli.js:299:28)
    at /Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/decaffeinate/dist/cli.js:231:42
    at step (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/tslib/tslib.js:143:27)
    at Object.next (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/Users/qnighy/.npm/_npx/59d73df66d985537/node_modules/tslib/tslib.js:114:62)
```

**Comment by eventualbuddha** [comment]
Looks like the [normalize stage is failing to insert a parenthesis](https://decaffeinate-project.org/repl/#?useCS2=false&useJSModules=false&loose=false&optionalChaining=false&evaluate=true&stage=NormalizeStage&code=foo%20-%3E%0A%20%20bar%0A%20%20%20%20baz%3A%2042%2C), yielding this:

```coffee

foo(->
  bar
    baz: 42,
)
```

It works if the trailing comma is removed.

**Comment by qnighy** [comment]
Thanks for the quick response! I really appreciate it.
