### ISSUE TITLE
Method call as parameter followed by other parameters sometimes throws SyntaxError

### ISSUE THREAD

**Issue by rkofman** [decaffeinate/decaffeinate#266]
Minimum reproducible error: `foo(bar(2), 2)`
Things that don't blow up: `foo(bar(2, 3), 2)`, `foo(bar(2))`, `foo(2, bar(2))`
[REPL link](https://decaffeinate.github.io/decaffeinate/repl/#?evaluate=true&code=foo(2%2C%20bar(2)%2C%203))

Stack trace below.

```
SyntaxError: Unexpected token (27:69)
  at Parser.pp.raise (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/location.js:22:13)
  at Parser.pp.unexpected (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/util.js:89:8)
  at Parser.pp.expect (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/util.js:83:33)
  at Parser.pp.parseCallExpressionArguments (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:344:12)
  at Parser.pp.parseSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:316:31)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:287:15)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:92:19)
  at Parser.pp.parseReturnStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:333:26)
  at Parser.pp.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:107:19)
  at Parser.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:30:22)
  at Parser.pp.parseBlockBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:529:21)
  at Parser.pp.parseBlock (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:510:8)
  at Parser.pp.parseFunctionBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:927:22)
  at Parser.parseFunctionBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:17:20)
  at Parser.pp.parseArrowExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:906:8)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:437:21)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:277:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseExprListItem (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:1046:16)
  at Parser.parseExprListItem (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:224:24)
  at Parser.pp.parseCallExpressionArguments (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:353:20)
  at Parser.pp.parseSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:316:31)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:287:15)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:151:23)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:92:19)
  at Parser.pp.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:163:19)
  at Parser.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:30:22)
  at Parser.pp.parseBlockBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:529:21)
  at Parser.pp.parseBlock (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:510:8)
  at Parser.pp.parseFunctionBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:927:22)
  at Parser.parseFunctionBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:17:20)
  at Parser.pp.parseFunction (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:647:8)
  at Parser.pp.parseFunctionExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:532:17)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:494:19)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:277:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseParenAndDistinguishExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:596:26)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:481:19)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:277:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseObjPropValue (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:818:99)
  at Parser.parseObjPropValue (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:307:13)
  at Parser.pp.parseObj (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:791:10)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:491:19)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:277:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseParenAndDistinguishExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:596:26)
  at Parser.pp.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:481:19)
  at Parser.parseExprAtom (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/jsx/index.js:18:22)
  at Parser.pp.parseExprSubscripts (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:277:19)
  at Parser.pp.parseMaybeUnary (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:257:19)
  at Parser.pp.parseExprOps (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:188:19)
  at Parser.pp.parseMaybeConditional (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:165:19)
  at Parser.pp.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:128:19)
  at Parser.parseMaybeAssign (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:454:20)
  at Parser.pp.parseExpression (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/expression.js:92:19)
  at Parser.pp.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:163:19)
  at Parser.parseStatement (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/plugins/flow.js:30:22)
  at Parser.pp.parseBlockBody (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:529:21)
  at Parser.pp.parseTopLevel (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/statement.js:36:8)
  at Parser.parse (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/parser/index.js:129:19)
  at Object.parse (/usr/local/lib/node_modules/decaffeinate/node_modules/babylon/lib/index.js:47:47)
  at addVariableDeclarations (/usr/local/lib/node_modules/decaffeinate/node_modules/add-variable-declarations/dist/add-variable-declarations.js:209:77)
  at Function.run (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:173:7)
  at /usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:9129:28
  at Array.forEach (native)
  at runStages (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:9128:10)
  at convert$1 (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:9121:10)
  at ReadStream.<anonymous> (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:9058:19)
  at emitNone (events.js:91:20)
  at ReadStream.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:934:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by alangpierce** [comment]
I ran into this, too. I think I have a fix for it, and I'll send out a PR soon.
