### ISSUE TITLE
Error: unexpected identifier crashes are not very debugable

### ISSUE THREAD

**Issue by andrewaustin** [decaffeinate/decaffeinate#413]
decaffeinate is crashing on a number of my coffeescript files with the error:

```coffee
===== apps/server/stanzaRouter.coffee
/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10471
        throw err;
        ^

Error: unexpected identifier
  at ParseError.Error (native)
  at new ParseError (/Users/andrew.austin/n/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:160:85)
  at Function.fromSource (/Users/andrew.austin/n/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:224:19)
  at Object.parse (/Users/andrew.austin/n/lib/node_modules/decaffeinate/node_modules/decaffeinate-parser/dist/decaffeinate-parser.umd.js:738:32)
  at parse$2 (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:8202:32)
  at Function.run (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:8234:17)
  at runStage (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10566:18)
  at /Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10550:21
  at Array.forEach (native)
  at runStages (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10549:10)
  at convert$1 (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10542:10)
  at ReadStream.<anonymous> (/Users/andrew.austin/n/lib/node_modules/decaffeinate/dist/decaffeinate.js:10465:19)
  at emitNone (events.js:72:20)
  at ReadStream.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:921:12)
  at nextTickCallbackWith2Args (node.js:442:9)
  at process._tickCallback (node.js:356:17)

```

Is there a good way to investigate these errors further?

**Comment by alangpierce** [comment]
I've seen these types of issues as well. It happens when there's a CoffeeScript parsing error. Presumably your code is valid CoffeeScript, so what's probably happening is the NormalizeStage is doing some cleanups on your CoffeeScript code, but due to a bug it results in invalid CoffeeScript.

The best way I know to track down the actual cause is to delete different parts of your code using the repl until you've isolated it to a much smaller file that still fails with the same error. Then you can change the "run to stage" option to see what happens at each stage. If my guess is right, you'll see output for NormalizeStage, but not for MainStage. Hopefully that should at least let you know what code to mess with to try to get decaffeinate to work. And, of course, if you could report the reduced failure case, that would be great.

I bet the error reporting could be improved with a solution similar to https://github.com/decaffeinate/decaffeinate/pull/272/files

**Comment by alangpierce** [comment]
Here's a relatively small test case for this type of issue: [repl](http://decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%7B%0A%20%20a%3A%20-%3E%0A%20%20%20%20return%20b%20c%2C%0A%20%20%20%20%20%20d%20e%2C%0A%20%20%20%20%20%20%20%20f%0A%20%20%20%20%20%20i%20j%2C%20k%2C%0A%7D)

**Comment by andrewaustin** [comment]
This is happening in a large number of files in our project, so I'm hoping to try to reduce the files down to reproducible cases sometime this week.

**Comment by alangpierce** [comment]
Thanks. The exception being thrown has the code location of the error, but the exception handler isn't using that information for this type of error, so currently I'm working on a fix to improve the error reporting so it gives more information about what's really going wrong. That should make it much more obvious where in the file the problem is.

**Comment by alangpierce** [comment]
@andrewaustin I just put up a PR that adds better error reporting. If you want, you can try it out in [my fork of the repl](http://www.alangpierce.com/decaffeinate-project.org/repl/#?evaluate=true&stage=full&code=%7B%0A%20%20a%3A%20-%3E%0A%20%20%20%20return%20b%20c%2C%0A%20%20%20%20%20%20d%20e%2C%0A%20%20%20%20%20%20%20%20f%0A%20%20%20%20%20%20g%20h%2C%20i%2C%0A%7D).
