### ISSUE TITLE
Support chain syntax

### ISSUE THREAD

**Issue by lunks** [decaffeinate/decaffeinate#51]
I'm exporting my controllers via angular using
```coffeescript
angular
  .module('app')
  .controller('MyCtrl', MyCtrl)
```

`decaffeinate` doesn't support this syntax. I'm getting the error:
```
Error: BUG! Could not fix range for FunctionApplication at line 8, column 1
    at fixRange (/opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/parse.js:127:11)
    at /opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/parse.js:41:5
    at traverse (/opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:36:23)
    at /opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:31:9
    at Array.forEach (native)
    at descend (/opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:22:32)
    at traverse (/opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:39:5)
    at /opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:31:9
    at Array.forEach (native)
    at descend (/opt/boxen/nodenv/versions/v0.12.7/lib/node_modules/decaffeinate/lib/utils/traverse.js:22:32)
```

If I change it and put everything in the same line, it successfully converts this chunk of code.

**Comment by eventualbuddha** [comment]
This is due to a bug in CoffeeScriptRedux. It does parse it correctly, but decaffeinate depends on knowing the correct position and text content of all parts of the program. CSR sometimes does not give this information correctly, and this is one such case. I expect to see a `MemberAccessOp` with raw string value of `angular\n  .module`, but instead I get one with `angular.module`, which is not what is in the actual source code.

This would probably be fixed by switching to the official CoffeeScript project for parsing, which is something I've considered.

**Comment by matthieu-ravey** [comment]
Hi, any update on this ?

**Comment by eventualbuddha** [comment]
Fixed in the latest version ([repl](http://decaffeinate.github.io/decaffeinate/repl/#?evaluate=false&code=angular%0A%20%20.module('app')%0A%20%20.controller('MyCtrl'%2C%20MyCtrl))).
