### ISSUE TITLE
decaffeinate pipe on macOS Sierra not working

### ISSUE THREAD

**Issue by clodal** [decaffeinate/decaffeinate#594]
Just installed decaffeinate with `npm install -g decaffeinate` on a macOS Sierra, but can't seem to get the example going. Is there something i'm missing?

$ echo "a = 1" | decaffeinate
```
/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:11722
    var options = Object.assign({ filename: name }, baseOptions);
                         ^
TypeError: undefined is not a function
  at Socket.<anonymous> (/usr/local/lib/node_modules/decaffeinate/dist/decaffeinate.js:11722:26)
  at Socket.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

$ npm -v
`4.0.5`

$ decaffeinate -h
```
decaffeinate [OPTIONS] PATH [PATH …]
decaffeinate [OPTIONS] < INPUT

Move your CoffeeScript source to JavaScript using modern syntax.

OPTIONS

  -h, --help       Display this help message.
  --keep-commonjs  Do not convert require and module.exports to import and export.
  --prefer-const   Use the const keyword for variables when possible.

EXAMPLES

  # Convert a .coffee file to a .js file.
  $ decaffeinate index.coffee

  # Pipe an example from the command-line.
  $ echo "a = 1" | decaffeinate

  # On OS X this may come in handy:
  $ pbpaste | decaffeinate | pbcopy

  # Process everything in a directory.
  $ decaffeinate src/

  # Redirect input from a file.
  $ decaffeinate < index.coffee
```

**Comment by clodal** [comment]
Sorry found the issue, was running an outdated version of node when running the global install. Reinstalled node and npm on my mac to the latest versions and ran decaffeinate and it works now. Thanks.

**Comment by alangpierce** [comment]
Thanks for the report. I just submitted #595 to make the node 4 requirement a little more clear.
